CREATE TABLE IF NOT EXISTS ROLE (
     ID_ROLE INTEGER AUTO_INCREMENT ,
     NAME VARCHAR (100) NOT NULL ,
     DESCRIPTION VARCHAR (100) NOT NULL ,
    PRIMARY KEY (ID_ROLE))
ENGINE = InnoDB
DEFAULT CHARSET = utf8;