CREATE TABLE IF NOT EXISTS `USER` (
     ID_USER INTEGER AUTO_INCREMENT ,
     FIRST_NAME VARCHAR (100) NOT NULL ,
     LAST_NAME VARCHAR (100) NOT NULL ,
     EMAIL VARCHAR (250) NOT NULL ,
     USERNAME VARCHAR (250) NOT NULL ,
     PASSWORD VARCHAR (250) NOT NULL ,
     BIRTHDATE TIMESTAMP NOT NULL ,
     IS_ENABLED TINYINT(1) NOT NULL DEFAULT 0 ,
     ID_ROLE INTEGER NOT NULL,
    PRIMARY KEY (ID_USER))
ENGINE = InnoDB
DEFAULT CHARSET = utf8;

CREATE INDEX IF NOT EXISTS `IDX_USER_ROLE` ON `USER` (`ID_ROLE`);

ALTER TABLE `USER` ADD CONSTRAINT FK_USER_ROLE FOREIGN KEY IF NOT EXISTS (ID_ROLE) REFERENCES ROLE (ID_ROLE);