CREATE TABLE IF NOT EXISTS EMAIL_VERIFICATION (
     ID_EMAIL_VERIFICATION INTEGER AUTO_INCREMENT ,
     TOKEN VARCHAR (500) NOT NULL ,
     EXPIRATION_TIME TIMESTAMP NOT NULL ,
     EXPIRED TINYINT(1) NOT NULL DEFAULT 0 ,
     ID_USER INTEGER NOT NULL,
    PRIMARY KEY (ID_EMAIL_VERIFICATION))
ENGINE = InnoDB
DEFAULT CHARSET = utf8;

CREATE INDEX IF NOT EXISTS `IDX_EMAIL_VERIFICATION_USER` ON `USER` (`ID_USER`);

ALTER TABLE EMAIL_VERIFICATION ADD CONSTRAINT FK_EMAIL_VERIFICATION_USER FOREIGN KEY IF NOT EXISTS (ID_USER) REFERENCES `USER` (ID_USER);