# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Update db url
      run: sed -i 's/${MARIADB_URL}/${{ secrets.MARIADB_URL }}/' src/main/resources/application-dev.yml

    - name: Update db username
      run: sed -i 's/${MARIADB_USER}/${{ secrets.MARIADB_USER }}/' src/main/resources/application-dev.yml

    - name: Update db password
      run: sed -i 's/${MARIADB_PASS}/${{ secrets.MARIADB_PASS }}/' src/main/resources/application-dev.yml

    - name: Update mail username
      run: sed -i 's/${MAIL_USER}/${{ secrets.MAIL_USER }}/' src/main/resources/application-dev.yml

    - name: Update mail password
      run: sed -i 's/${MAIL_PASS}/${{ secrets.MAIL_PASS }}/' src/main/resources/application-dev.yml


        # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3

